### PR TITLE
posts(learning-to-fly-pt3): Remove semantic ambiguity

### PR DESCRIPTION
**Pull request by alexxroche**
"calling a function" means invoking a function in your code. "naming a function" is that impossible task that is solved the moment that you have to maintain backwards compatibility and realise the perfect name for your function. e.g. `fn from_chromosome()` is better than `fn create()`.

### CODE REVIEW

**Comment by Patryk27** [comment]
That's a nice one 🙂

Before I merge, would you mind naming the commit `posts(learning-to-fly-pt3): Remove semantic ambiguity`?

**Comment by alexxroche** [comment]
Hope I changed the title correctly. (I set the pull request so that you could edit it - but I'm more than happy to make any changes that you need.)

**Comment by Patryk27** [comment]
Oh, I meant the commit title (e.g. via `git commit --amend`) - that's the one I cannot change (since it's inside your branch).

**Comment by alexxroche** [comment]
Like this? https://github.com/alexxroche/website/commit/0b393df2a97e9c556944ac5fa3ab79bb3f1aa7d5

**Comment by Patryk27** [comment]
Yeps, like this; thanks!

**Pull request merged**
